# my global config
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "JenkinServer"
    static_configs:
      - targets: ["10.0.0.170:9100"]

  - job_name: "Ansible_Feb"
    static_configs:
      - targets: ["10.0.0.109:9100"]